apiVersion: v1
kind: Service
metadata:  
  name: nginx-cluster-ip-service
spec:
  selector:    
    app: nginx
  ports:  
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP


#To give Cluster IP service access externally, use the Kubernetes Proxy
#    kubectl proxy --port=8080


#Navigate through the Kubernetes API to access this service
#    http://localhost:8080/api/v1/proxy/namespaces/<NAMESPACE>/services/<SERVICE-NAME>:<PORT-NAME>/