apiVersion: v1
kind: Service
metadata:
  name: ecom-backend-secret-env-var-service
spec:
  type: NodePort
  selector:
    app: ecom-backend-secret-env-var
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: ecom-backend-secret-env-file-service
spec:
  type: NodePort
  selector:
    app: ecom-backend-secret-env-file
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30003
