apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  .env: ZGF0YWJhc2VfdXJsOiAibXlzcWw6Ly9lY29tLWRiOjMzMDYvc2hvcCIKY2FjaGVfc2l6ZTogIjEwMDAiCnBheW1lbnRfZ2F0ZXdheV91cmw6ICJodHRwczovL3BheW1lbnQtZ2F0ZXdheS5leGFtcGxlLmNvbSIKbWF4X2NhcnRfaXRlbXM6ICI1MCIKc2Vzc2lvbl90aW1lb3V0OiAiMzYwMCI=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-backend-secret-env-file-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-backend-secret-env-file
  template:
    metadata:
      labels:
        app: ecom-backend-secret-env-file
    spec:
      containers:
      - name: ecom-backend-secret-env-file
        image: 100xdevs/env-backend
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: env-file
          readOnly: true
          mountPath: "/app/config"
      volumes:
      - name: env-file
        secret:
          secretName: dotfile-secret
