apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  database_url: bXlzcWw6Ly9lY29tLWRiOjMzMDYvc2hvcA==
  cache_size: MTAwMA==
  payment_gateway_url: aHR0cHM6Ly9wYXltZW50LWdhdGV3YXkuZXhhbXBsZS5jb20=
  max_cart_items: NTA=
  session_timeout: MzYwMA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-backend-secret-env-var-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-backend-secret-env-var
  template:
    metadata:
      labels:
        app: ecom-backend-secret-env-var
    spec:
      containers:
      - name: ecom-backend-secret-env-var
        image: 100xdevs/env-backend
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: database_url
        - name: CACHE_SIZE
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: cache_size
        - name: PAYMENT_GATEWAY_URL
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: payment_gateway_url
        - name: MAX_CART_ITEMS
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: max_cart_items
        - name: SESSION_TIMEOUT
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: session_timeout
